services:
  collector:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "7071:7071"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=kusho
      - MYSQL_PASSWORD=kusho_password
      - MYSQL_DATABASE=kusho_traffic
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kusho_traffic
      - MYSQL_USER=kusho
      - MYSQL_PASSWORD=kusho_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ../migrations:/docker-entrypoint-initdb.d
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
  mysql_data:
